name: venkyvajrala_greetings
description: "This action will greet anyone with name"
branding:
  icon: 'award'
  color: 'green'
inputs:
  whom-to-greet:
    description: "Name of the person to greet"
    default: "World"

outputs:
  time:
    description: "The time we greeted you"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.whom-to-greet }}